name: norminette

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  norminette:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: pip
      uses: BSFishy/pip-action@v1
      with:
        packages: norminette
        upgrade: true
    -name: check norme
    run: norminette src
